apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
kind: ConfigMap
metadata:
  namespace: grafana
  name: grafana-agent
apiVersion: v1
data:
  agent.yaml: |
    metrics:
      wal_directory: /var/lib/agent/wal
      global:
        scrape_interval: 60s
        external_labels:
          cluster: kong
        remote_write:
        - url: https://metrics.prd.obs.fr-par.scw.cloud/api/v1/push
          headers:
            X-Token: 41RJbykgTt1E6-607Kaj-vdAT4Eo10iMLXE5RHmMsmPRUTBsB07TLPh_CsbU-Xyx
      configs:
      - name: agent
        scrape_configs:
          - job_name: agent
            static_configs:
              - targets: ['127.0.0.1:12345']
      - name: everything
        scrape_configs:
          - job_name: kubernetes-service-endpoints
            kubernetes_sd_configs:
            - role: endpoints
            relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: kubernetes_namespace
            - source_labels: [__meta_kubernetes_service_name]
              action: replace
              target_label: kubernetes_name
